name: caretaker
on:
  push:
    branches:
      - main
  schedule:
    - cron:  '0 2 1 * *'
jobs:
  deploy:
    runs-on:
      - codebuild-caretaker-${{ github.run_id }}-${{ github.run_attempt }}
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
      - uses: actions/setup-node@v4
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.ROLE }}
          aws-region: us-east-1
      - run: npm install -g aws-cdk
      - run: npm install -g aws-cdk-lib
      - run: python -m pip install --upgrade pip
      - run: pip install -r requirements.txt --upgrade
      - run: cdk deploy --all --require-approval never